import {
  BookHeart,
  BriefcaseBusiness,
  Calendar,
  Cloud,
  Code,
  Database,
  GraduationCap,
  Headphones,
  Image,
  Linkedin,
  Mail,
  MessageCircleCode,
  MessageCircleQuestionIcon,
  Newspaper,
  ShoppingCart,
  Youtube,
} from "lucide-react";

export const templates = [
  {
    id: 1,
    icon: <MessageCircleCode className="text-white w-12 h-12" />,
    iconColor: "#f9a6ff",
    name: "AI Customer Support Agent",
    description:
      "A smart chatbot for your website that answers customer questions instantly. It uses your own documents (FAQs, product guides) as a knowledge base to provide accurate, context-aware responses, reducing the load on your support team.",
    category: "Customer Support",
    tags: ["chatbot", "support", "RAG", "knowledge base", "AI"],
    nodes: [
      "Chat Bot Trigger",
      "Knowledge Base",
      "Google Chat",
      "Send Chat Bot Response",
    ],
    link: "https://d4g.app/JsMwv5",
  },
  {
    id: 2,
    icon: <BriefcaseBusiness className="text-white w-12 h-12" />,
    iconColor: "#a6c1ff",
    name: "Automated Job Search Alerter",
    description:
      "Runs on a schedule to search for new job postings based on your criteria (keywords, country, minimum salary). It then formats the list of jobs and sends it to you via Telegram, so you never miss an opportunity.",
    category: "Career & Job Search",
    tags: ["jobs", "search", "automation", "career", "telegram"],
    nodes: [
      "Cron Trigger",
      "Jobs Search",
      "JSON to Text",
      "Google Chat",
      "Google Sheets",
      "Send Telegram Message",
    ],
    link: "https://d4g.app/GSGTWq",
  },
  {
    id: 3,
    icon: <Newspaper className="text-white w-12 h-12" />,
    iconColor: "#29ffdb",
    name: "Automated Daily News Tweeter",
    description:
      "This template automatically fetches the latest news on a specific topic once a day, uses an AI to write a compelling tweet about it, and posts it to your Twitter account. Keep your audience engaged with fresh content without any manual effort.",
    category: "Social Media Automation",
    tags: ["twitter", "automation", "news", "content creation", "cron"],
    nodes: ["Cron Trigger", "AI Web Search", "OpenAI Chat", "Tweet Post"],
    link: "https://d4g.app/Cn4sDf",
  },
  {
    id: 4,
    icon: <Calendar className="text-white w-12 h-12" />,
    iconColor: "#85ff8b",
    name: "Telegram Meeting Scheduler Bot",
    description:
      "Allows users to find and see available meeting slots directly within Telegram. The bot interacts with the user to understand their request and fetches available times from your Cal.com schedule, making booking appointments seamless.",
    category: "Productivity",
    tags: ["telegram", "bot", "scheduling", "cal.com", "assistant"],
    nodes: [
      "Telegram Trigger",
      "Get Cal.com Schedule",
      "JSON to Text",
      "OpenAI Chat",
      "Book Cal.com Meeting",
      "Send Telegram Message",
    ],
    link: "https://d4g.app/VZRPU1",
  },
  {
    id: 5,
    icon: <Mail className="text-white w-12 h-12" />,
    iconColor: "#ffe76e",
    name: "Gmail Summarizer to Telegram",
    description:
      "Triggers whenever you receive a new email in Gmail. It then uses an AI to summarize the email's content and sends the summary to you via a Telegram message for a quick overview on the go.",
    category: "Personal Productivity",
    tags: ["email", "gmail", "telegram", "automation", "summarization", "AI"],
    nodes: ["Gmail Trigger", "OpenAI Chat", "Send Telegram Message"],
    link: "https://d4g.app/T1mtFS",
  },
  {
    id: 6,
    icon: <Image className="text-white w-12 h-12" />,
    iconColor: "#ffc299",
    name: "Generative AI Media Studio",
    description:
      "A simple workflow for creative content generation. You provide a text prompt via Telegram, and the agent generates both a unique AI image using Google Imagen and a short AI music clip using Google Lyria, sending them back to you.",
    category: "Content Creation",
    tags: ["GenAI", "images", "music", "AI", "google", "telegram", "creative"],
    nodes: [
      "Telegram Trigger",
      "Imagen AI Images",
      "Lyria AI Music",
      "Send Telegram Media Message",
    ],
    link: "https://d4g.app/aqFLTE",
  },
  {
    id: 7,
    icon: <Linkedin className="text-white w-12 h-12" />,
    iconColor: "#9361ff",
    name: "Content Repurposing for LinkedIn",
    description:
      "This agent takes a link to a web article or blog post, ingests its content, and then leverages an AI to write a professional LinkedIn post summarizing the key points, complete with relevant hashtags.",
    category: "Social Media & Marketing",
    tags: ["linkedin", "content creation", "marketing", "automation", "AI"],
    nodes: [
      "Chat Bot Trigger",
      "Knowledge Base",
      "Google Chat",
      "LinkedIN Post",
    ],
    link: "https://d4g.app/bP0gQ4",
  },
  {
    id: 8,
    icon: <Cloud className="text-white w-12 h-12" />,
    iconColor: "#a6c1ff",
    name: "Weather API Bot",
    description:
      "A simple agent that runs on a schedule, calls an external weather API for a specific location, extracts the relevant temperature and conditions, and posts a formatted daily weather update.",
    category: "Utilities",
    tags: ["api", "weather", "cron", "json", "utility"],
    nodes: [
      "Cron Trigger",
      "API Call",
      "Extract JSON",
      "Text Join",
      "Tweet Post",
    ],
    link: "https://d4g.app/QaP83x",
  },
  {
    id: 9,
    icon: <Headphones className="text-white w-12 h-12" />,
    iconColor: "#29ffdb",
    name: "Text-to-Audiobook Narrator",
    description:
      "Convert any piece of text into a high-quality audio narration. Simply paste your text, and this agent will use Eleven Labs' Text-to-Speech service to generate an audio file and send it to you.",
    category: "Audio & Content Creation",
    tags: ["audio", "tts", "narration", "elevenlabs", "text to speech"],
    nodes: [
      "Telegram Trigger",
      "Text to Speech",
      "Send Telegram Media Message",
    ],
    link: "https://d4g.app/Us1KRW",
  },
  {
    id: 10,
    icon: <Youtube className="text-white w-12 h-12" />,
    iconColor: "#f9a6ff",
    name: "AI Video to YouTube",
    description:
      "The purpose of this agent is to generate AI videos at a given set of interval and then upload it to YouTube automatically. All you need to do is choose the topic of the videos and connect your YouTube account.",
    category: "Social Media Automation",
    tags: ["video", "AI", "YouTube", "automation"],
    nodes: ["Cron Trigger", "Google Veo", "YouTube Upload"],
    link: "https://d4g.app/AtBfud",
  },
  {
    id: 11,
    icon: <GraduationCap className="text-white w-12 h-12" />,
    iconColor: "#85ff8b",
    name: "AI Tutor",
    description:
      "An AI Tutor Agent that can guide users to learn a specific topic from a particular knowledge level, with the option to take custom references from books.",
    category: "Utilities",
    tags: ["AI", "tutor", "knowledge", "learning", "automation"],
    nodes: [
      "Chat Bot Trigger",
      "Knowledge Base",
      "Google Chat",
      "Send Chat Bot Response",
    ],
    link: "https://d4g.app/DpagS3",
  },
  {
    id: 12,
    icon: <ShoppingCart className="text-white w-12 h-12" />,
    iconColor: "#ffe76e",
    name: "Product Availability Checker",
    description:
      "This agent assists in determining the availability of a product via Telegram. Simply paste the product link into a Telegram chat, and it will send you a confirmation if the product is available or not.",
    category: "Productivity",
    tags: ["product", "availability", "telegram", "automation"],
    nodes: [
      "Telegram Trigger",
      "Get URL Data",
      "Google Chat",
      "Send Telegram Message",
    ],
    link: "https://d4g.app/8Yk974",
  },
  {
    id: 13,
    icon: <BookHeart className="text-white w-12 h-12" />,
    iconColor: "#f9a6ff",
    name: "AI Companion",
    description:
      "Create your own AI Girlfriend that works through Telegram. Works with both Audio and Text. The AI can answer your questions, tell you jokes, and even make you laugh. Works with Telegram and Google Chat.",
    category: "Misc",
    tags: ["AI", "companion", "telegram", "google chat", "personal"],
    nodes: [
      "Telegram Trigger",
      "Google Chat",
      "Send Telegram Message",
      "Speech to Text",
      "Text to Speech",
      "Send Telegram Media Message",
    ],
    link: "https://d4g.app/jkinQE",
  },
  {
    id: 14,
    icon: <Code className="text-white w-12 h-12" />,
    iconColor: "#ff8e61",
    name: "Leetcode Daily Problem Solver",
    description:
      "This agent solves a daily Leetcode problem, guides you through the solution, and sends the solution to you via Telegram. It uses an AI to generate the solution and sends it to you via Telegram.",
    category: "Programming",
    tags: ["leetcode", "problem", "telegram", "automation"],
    nodes: [
      "Chat Bot Trigger",
      "Get URL Data",
      "OpenAI Chat",
      "Send Chat Bot Response",
    ],
    link: "https://d4g.app/EEHJwN",
  },
  {
    id: 15,
    icon: <MessageCircleQuestionIcon className="text-white w-12 h-12" />,
    iconColor: "#ff6188",
    name: "Kahoot Chatbot Agent",
    description:
      "This chatbot agent presents you with multiple-choice questions similar to those on Kahoot, based on the website link you’ve provided. You can customize various parameters to shape the quiz’s difficulty and type.",
    category: "Misc",
    tags: ["kahoot", "quiz", "telegram", "automation"],
    nodes: [
      "Chat Bot Trigger",
      "Get URL Data",
      "OpenAI Chat",
      "Send Chat Bot Response",
    ],
    link: "https://d4g.app/QnQ0ix",
  },
  {
    id: 16,
    icon: <Database className="text-white w-12 h-12" />,
    iconColor: "#616eff",
    name: "Talk to your Database",
    description:
      "This AI agent can converse with your database and execute custom queries based on the message you provide. Uses PostgreSQL Custom Query node as a tool to fetch data from your database.",
    category: "Programming",
    tags: ["database", "postgresql", "custom query", "automation"],
    nodes: [
      "Chat Bot Trigger",
      "PostgreSQL Custom Query",
      "Send Chat Bot Response",
    ],
    link: "https://d4g.app/6gL1U6",
  },
];

export const categories = Array.from(new Set(templates.map((t) => t.category)));
export const allTags = Array.from(new Set(templates.flatMap((t) => t.tags)));
